name: 'Setup VSTest.Console.exe'
description: 'Uses VSWhere.exe to locate latest VSTest.Console & put it into the PATH'
author: 'Malcolm Nixon'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'download'
  color: 'purple'
